namespace BibleReader.Api;

/// <summary>66 livros protestantes — contagens de capítulos (total 1189).</summary>
public static class BibleCanon
{
    public record BookDef(int Order, string Slug, string Name, string Abbreviation, int ChapterCount);

    public static readonly BookDef[] Protestant =
    {
        new(1, "genesis", "Gênesis", "Gn", 50),
        new(2, "exodo", "Êxodo", "Êx", 40),
        new(3, "levitico", "Levítico", "Lv", 27),
        new(4, "numeros", "Números", "Nm", 36),
        new(5, "deuteronomio", "Deuteronômio", "Dt", 34),
        new(6, "josue", "Josué", "Js", 24),
        new(7, "juizes", "Juízes", "Jz", 21),
        new(8, "rute", "Rute", "Rt", 4),
        new(9, "1-samuel", "1 Samuel", "1Sm", 31),
        new(10, "2-samuel", "2 Samuel", "2Sm", 24),
        new(11, "1-reis", "1 Reis", "1Rs", 22),
        new(12, "2-reis", "2 Reis", "2Rs", 25),
        new(13, "1-cronicas", "1 Crônicas", "1Cr", 29),
        new(14, "2-cronicas", "2 Crônicas", "2Cr", 36),
        new(15, "esdras", "Esdras", "Ed", 10),
        new(16, "neemias", "Neemias", "Ne", 13),
        new(17, "ester", "Ester", "Et", 10),
        new(18, "jo", "Jó", "Jó", 42),
        new(19, "salmos", "Salmos", "Sl", 150),
        new(20, "proverbios", "Provérbios", "Pv", 31),
        new(21, "eclesiastes", "Eclesiastes", "Ec", 12),
        new(22, "cantares", "Cantares de Salomão", "Ct", 8),
        new(23, "isaias", "Isaías", "Is", 66),
        new(24, "jeremias", "Jeremias", "Jr", 52),
        new(25, "lamentacoes", "Lamentações", "Lm", 5),
        new(26, "ezequiel", "Ezequiel", "Ez", 48),
        new(27, "daniel", "Daniel", "Dn", 12),
        new(28, "oseias", "Oséias", "Os", 14),
        new(29, "joel", "Joel", "Jl", 3),
        new(30, "amos", "Amós", "Am", 9),
        new(31, "obadias", "Obadias", "Ob", 1),
        new(32, "jonas", "Jonas", "Jn", 4),
        new(33, "miqueias", "Miquéias", "Mq", 7),
        new(34, "naum", "Naum", "Na", 3),
        new(35, "habacuque", "Habacuque", "Hc", 3),
        new(36, "sofonias", "Sofonias", "Sf", 3),
        new(37, "ageu", "Ageu", "Ag", 2),
        new(38, "zacarias", "Zacarias", "Zc", 14),
        new(39, "malaquias", "Malaquias", "Ml", 4),
        new(40, "mateus", "Mateus", "Mt", 28),
        new(41, "marcos", "Marcos", "Mc", 16),
        new(42, "lucas", "Lucas", "Lc", 24),
        new(43, "joao", "João", "Jo", 21),
        new(44, "atos", "Atos", "At", 28),
        new(45, "romanos", "Romanos", "Rm", 16),
        new(46, "1-corintios", "1 Coríntios", "1Co", 16),
        new(47, "2-corintios", "2 Coríntios", "2Co", 13),
        new(48, "galatas", "Gálatas", "Gl", 6),
        new(49, "efesios", "Efésios", "Ef", 6),
        new(50, "filipenses", "Filipenses", "Fp", 4),
        new(51, "colossenses", "Colossenses", "Cl", 4),
        new(52, "1-tessalonicenses", "1 Tessalonicenses", "1Ts", 5),
        new(53, "2-tessalonicenses", "2 Tessalonicenses", "2Ts", 3),
        new(54, "1-timoteo", "1 Timóteo", "1Tm", 6),
        new(55, "2-timoteo", "2 Timóteo", "2Tm", 4),
        new(56, "tito", "Tito", "Tt", 3),
        new(57, "filemom", "Filemom", "Fm", 1),
        new(58, "hebreus", "Hebreus", "Hb", 13),
        new(59, "tiago", "Tiago", "Tg", 5),
        new(60, "1-pedro", "1 Pedro", "1Pe", 5),
        new(61, "2-pedro", "2 Pedro", "2Pe", 3),
        new(62, "1-joao", "1 João", "1Jo", 5),
        new(63, "2-joao", "2 João", "2Jo", 1),
        new(64, "3-joao", "3 João", "3Jo", 1),
        new(65, "judas", "Judas", "Jd", 1),
        new(66, "apocalipse", "Apocalipse", "Ap", 22),
    };

    public static int TotalChapters => Protestant.Sum(b => b.ChapterCount);
}
